apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: storage-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Increase body size for upload
    nginx.ingress.kubernetes.io/proxy-body-size: "0" 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - minio.obaven.org
    - s3.obaven.org
    secretName: minio-tls
  rules:
  - host: minio.obaven.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
  - host: s3.obaven.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
