apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-system

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    version: 12.8.10
    releaseName: minio
    namespace: storage-system
    valuesFile: values.yaml

resources:
  - rotation-config.yaml
